<?php
  session_start();
  include("top.php");
?>
<div class="footer_links">
  <h2>Általános szerzősédi feltételek</h2>
  <h3>1. Bevezetés:</h3>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Condimentum mattis pellentesque id nibh. Iaculis urna id volutpat lacus laoreet non curabitur gravida. Semper quis lectus nulla at. Non curabitur gravida arcu ac tortor. At erat pellentesque adipiscing commodo elit at imperdiet. Eu volutpat odio facilisis mauris sit amet massa vitae tortor. Bibendum ut tristique et egestas quis. Quis commodo odio aenean sed adipiscing diam donec adipiscing tristique. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Egestas purus viverra accumsan in. Sed velit dignissim sodales ut eu sem.
  <h3>2. A Honlap használata, rendelés:</h3>
  Pellentesque habitant morbi tristique senectus et netus et malesuada. Cursus euismod quis viverra nibh cras pulvinar mattis nunc sed. Volutpat est velit egestas dui id ornare arcu. Magna etiam tempor orci eu lobortis elementum. Mauris a diam maecenas sed enim ut. Cras ornare arcu dui vivamus arcu felis. Pretium quam vulputate dignissim suspendisse in est ante in. A lacus vestibulum sed arcu. A condimentum vitae sapien pellentesque habitant. Sit amet purus gravida quis blandit turpis cursus in. A cras semper auctor neque vitae tempus quam. Morbi tristique senectus et netus et malesuada fames ac. Eu consequat ac felis donec et odio pellentesque diam. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Viverra nam libero justo laoreet sit amet. Mauris pellentesque pulvinar pellentesque habitant morbi. Consectetur libero id faucibus nisl tincidunt. Arcu bibendum at varius vel pharetra vel turpis. Pharetra sit amet aliquam id diam maecenas.
  <h3>3. Fizetés, szállítás:</h3>
  Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Vitae tortor condimentum lacinia quis. Tempor orci eu lobortis elementum nibh tellus molestie nunc non. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Pharetra et ultrices neque ornare aenean euismod elementum nisi quis. Volutpat est velit egestas dui. Dignissim sodales ut eu sem integer vitae. Ornare arcu dui vivamus arcu felis bibendum ut tristique. Integer vitae justo eget magna fermentum. Est pellentesque elit ullamcorper dignissim. Interdum posuere lorem ipsum dolor sit amet consectetur. Consectetur a erat nam at lectus urna. Euismod quis viverra nibh cras pulvinar mattis nunc sed. Tincidunt id aliquet risus feugiat in ante metus. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget nullam. Velit sed ullamcorper morbi tincidunt ornare massa eget. Mattis nunc sed blandit libero volutpat sed. Amet luctus venenatis lectus magna fringilla urna porttitor. Nulla porttitor massa id neque aliquam vestibulum morbi blandit cursus.
  <h3>4. Elállás joga:</h3>
  Gravida in fermentum et sollicitudin ac orci. Massa sapien faucibus et molestie ac feugiat sed lectus vestibulum. Molestie nunc non blandit massa. Dignissim convallis aenean et tortor. Dui sapien eget mi proin sed libero enim. At augue eget arcu dictum varius. Ipsum suspendisse ultrices gravida dictum fusce. Rutrum quisque non tellus orci. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Dignissim convallis aenean et tortor at risus viverra adipiscing at.
  <h3>5. 30 napos visszavásárlási garancia:</h3>
  Odio eu feugiat pretium nibh ipsum consequat. Iaculis eu non diam phasellus. Nunc mi ipsum faucibus vitae. Nisi scelerisque eu ultrices vitae. Vulputate sapien nec sagittis aliquam malesuada. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi. Auctor augue mauris augue neque gravida. Libero volutpat sed cras ornare. Enim nec dui nunc mattis enim ut tellus elementum sagittis. Eget dolor morbi non arcu risus quis.
  <h3>6. Jótállás:</h3>
  Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Odio eu feugiat pretium nibh. Purus semper eget duis at tellus at urna condimentum. Massa tempor nec feugiat nisl pretium fusce id velit. Ac auctor augue mauris augue neque. Sagittis id consectetur purus ut faucibus pulvinar elementum integer enim. Elit pellentesque habitant morbi tristique senectus et. Egestas purus viverra accumsan in. Lacus vel facilisis volutpat est velit egestas. Non blandit massa enim nec dui nunc mattis enim ut. Consequat semper viverra nam libero. Ultricies tristique nulla aliquet enim tortor at auctor urna. Volutpat ac tincidunt vitae semper quis lectus nulla. Leo a diam sollicitudin tempor id eu nisl. Id eu nisl nunc mi ipsum faucibus vitae. Nullam ac tortor vitae purus faucibus ornare.
  <h3>7. Kellékszavatosság:</h3>
  Pharetra convallis posuere morbi leo urna molestie at elementum eu. Auctor elit sed vulputate mi sit amet mauris commodo. Laoreet suspendisse interdum consectetur libero id faucibus nisl. Turpis massa sed elementum tempus. Phasellus faucibus scelerisque eleifend donec pretium. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Aliquet bibendum enim facilisis gravida neque convallis a. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Orci sagittis eu volutpat odio facilisis mauris sit amet massa. At imperdiet dui accumsan sit amet nulla facilisi morbi. Adipiscing commodo elit at imperdiet dui accumsan sit amet. Et malesuada fames ac turpis egestas maecenas.
  <h3>8. Termékszavatosság:</h3>
  Ac ut consequat semper viverra nam. Faucibus scelerisque eleifend donec pretium vulputate sapien. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Egestas sed sed risus pretium. Morbi tristique senectus et netus et. In nulla posuere sollicitudin aliquam ultrices sagittis orci. Integer enim neque volutpat ac tincidunt vitae. Urna porttitor rhoncus dolor purus non. Eu non diam phasellus vestibulum lorem sed risus. Ut faucibus pulvinar elementum integer enim. Nisi vitae suscipit tellus mauris a diam. Velit egestas dui id ornare arcu odio ut sem nulla. Bibendum arcu vitae elementum curabitur vitae nunc sed. Gravida in fermentum et sollicitudin ac orci. Sit amet consectetur adipiscing elit. Varius morbi enim nunc faucibus a pellentesque sit amet porttitor. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Congue eu consequat ac felis. Id nibh tortor id aliquet lectus proin nibh nisl. Sit amet commodo nulla facilisi nullam vehicula ipsum a.
  <h3>9. Visszaküldés:</h3>
  Convallis aenean et tortor at risus viverra adipiscing. Etiam tempor orci eu lobortis elementum nibh. Ut sem viverra aliquet eget sit amet tellus. Dolor magna eget est lorem ipsum. Nisi lacus sed viverra tellus. Interdum varius sit amet mattis vulputate enim nulla aliquet. Sed adipiscing diam donec adipiscing tristique risus nec feugiat in. Elementum sagittis vitae et leo duis ut diam quam. Pharetra vel turpis nunc eget. Sit amet nulla facilisi morbi. Velit sed ullamcorper morbi tincidunt ornare massa. Mollis nunc sed id semper risus in. Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Id diam vel quam elementum pulvinar etiam non quam lacus. Non arcu risus quis varius quam quisque id. Etiam non quam lacus suspendisse faucibus. Lacinia quis vel eros donec ac odio tempor. At urna condimentum mattis pellentesque id nibh tortor id.
  <h3>10. Tulajdonjog fenntartása:</h3>
  Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Lacinia quis vel eros donec ac odio. Quam vulputate dignissim suspendisse in. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Imperdiet massa tincidunt nunc pulvinar sapien et. Iaculis nunc sed augue lacus viverra vitae. Faucibus turpis in eu mi. Orci a scelerisque purus semper eget duis. Morbi quis commodo odio aenean sed adipiscing diam donec. Dictum fusce ut placerat orci nulla. Quis auctor elit sed vulputate mi sit amet. Vulputate dignissim suspendisse in est ante in. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Mattis aliquam faucibus purus in.
  <h3>11. Személyes adatok védelme:</h3>
  Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Nulla aliquet porttitor lacus luctus accumsan tortor posuere. Faucibus in ornare quam viverra orci sagittis eu volutpat. Elementum facilisis leo vel fringilla est ullamcorper. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Id cursus metus aliquam eleifend. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Ultrices neque ornare aenean euismod. Magna ac placerat vestibulum lectus. Euismod elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Interdum posuere lorem ipsum dolor. Sit amet justo donec enim diam vulputate ut pharetra sit.
  <h3>12. Adatkezelési nyilatkozat:</h3>
  Donec pretium vulputate sapien nec sagittis aliquam. Vulputate odio ut enim blandit volutpat maecenas. Orci nulla pellentesque dignissim enim sit amet venenatis urna. Mauris vitae ultricies leo integer malesuada nunc vel risus. Morbi leo urna molestie at. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Dui nunc mattis enim ut tellus elementum sagittis. Quis blandit turpis cursus in hac habitasse. Velit dignissim sodales ut eu sem. Dui id ornare arcu odio ut sem nulla pharetra. Quam viverra orci sagittis eu volutpat odio facilisis mauris.
  <h3>13. Hírlevél:</h3>
  Sodales ut etiam sit amet nisl purus in. Penatibus et magnis dis parturient montes nascetur ridiculus mus mauris. Ut lectus arcu bibendum at varius vel pharetra vel. Auctor urna nunc id cursus metus aliquam. Enim ut sem viverra aliquet eget sit amet tellus. Ultrices vitae auctor eu augue ut lectus arcu bibendum. Porta lorem mollis aliquam ut porttitor leo a. Sed vulputate mi sit amet mauris commodo quis imperdiet massa. Pretium vulputate sapien nec sagittis aliquam. Nullam ac tortor vitae purus faucibus ornare suspendisse. Mattis enim ut tellus elementum sagittis vitae et. Odio eu feugiat pretium nibh ipsum consequat. Sit amet tellus cras adipiscing enim eu turpis egestas pretium. Diam maecenas ultricies mi eget mauris pharetra et ultrices neque. Arcu ac tortor dignissim convallis. Gravida arcu ac tortor dignissim convallis.
  <h3>14. Jogorvoslat:</h3>
  Posuere sollicitudin aliquam ultrices sagittis orci. Non blandit massa enim nec dui. At erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Enim nec dui nunc mattis enim ut tellus elementum sagittis. Amet commodo nulla facilisi nullam vehicula ipsum. Lacus viverra vitae congue eu consequat ac felis donec et. Molestie nunc non blandit massa enim nec dui nunc. Ac ut consequat semper viverra nam libero justo laoreet sit. Facilisis volutpat est velit egestas dui id. Enim praesent elementum facilisis leo vel fringilla. Vel turpis nunc eget lorem dolor sed viverra ipsum nunc. Nibh sed pulvinar proin gravida. Morbi tincidunt augue interdum velit euismod in. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum.
</div>
<?php
  echo file_get_contents("html\bottom.html");
?>
