<?php
  session_start();
  include("top.php");
?>
<div class="footer_links">
  <h2>Szállítási feltételek</h2>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisi scelerisque eu ultrices vitae auctor eu augue. Ultricies mi quis hendrerit dolor magna eget. Diam maecenas sed enim ut sem viverra. Faucibus vitae aliquet nec ullamcorper sit amet. In ante metus dictum at. Velit scelerisque in dictum non consectetur a erat nam. Morbi tincidunt ornare massa eget egestas. Sit amet nisl suscipit adipiscing. Sapien nec sagittis aliquam malesuada. Augue eget arcu dictum varius duis at consectetur lorem. Senectus et netus et malesuada. Amet facilisis magna etiam tempor orci eu lobortis elementum. Mauris nunc congue nisi vitae suscipit. Eget nunc lobortis mattis aliquam faucibus purus in massa. Porta lorem mollis aliquam ut.

  Porttitor massa id neque aliquam vestibulum morbi blandit cursus. Posuere ac ut consequat semper viverra. Dignissim convallis aenean et tortor at risus viverra adipiscing. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Vulputate dignissim suspendisse in est ante in nibh mauris. Donec et odio pellentesque diam volutpat commodo sed egestas egestas. Egestas dui id ornare arcu odio ut sem. In hac habitasse platea dictumst quisque sagittis. Sed viverra tellus in hac habitasse platea dictumst vestibulum. Arcu non odio euismod lacinia at. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Egestas maecenas pharetra convallis posuere. Malesuada fames ac turpis egestas sed tempus. Hendrerit dolor magna eget est lorem ipsum. Sit amet consectetur adipiscing elit duis. Nunc faucibus a pellentesque sit. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat.

  Senectus et netus et malesuada fames ac turpis. Hendrerit gravida rutrum quisque non tellus orci ac auctor augue. Nisl pretium fusce id velit ut tortor pretium viverra. Consequat semper viverra nam libero justo. Feugiat nisl pretium fusce id velit ut. Consequat nisl vel pretium lectus quam id leo in. Dignissim enim sit amet venenatis urna cursus eget nunc scelerisque. Id interdum velit laoreet id. Maecenas pharetra convallis posuere morbi leo urna molestie at elementum. Facilisi nullam vehicula ipsum a arcu. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit amet. Ultrices vitae auctor eu augue ut lectus.

  Augue ut lectus arcu bibendum at varius. Interdum consectetur libero id faucibus nisl tincidunt eget nullam non. Vel pharetra vel turpis nunc. Et netus et malesuada fames ac turpis egestas integer. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. At risus viverra adipiscing at. Vulputate odio ut enim blandit volutpat maecenas volutpat. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Placerat orci nulla pellentesque dignissim. At quis risus sed vulputate odio ut enim blandit volutpat. Viverra adipiscing at in tellus integer.

  Enim diam vulputate ut pharetra sit. Justo donec enim diam vulputate ut pharetra. Lacus vel facilisis volutpat est velit egestas dui id ornare. Justo nec ultrices dui sapien eget mi proin sed. Nunc scelerisque viverra mauris in. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis. Amet purus gravida quis blandit turpis cursus in. Lacinia quis vel eros donec ac odio tempor orci. Interdum velit laoreet id donec ultrices tincidunt. Vitae ultricies leo integer malesuada nunc vel. Velit dignissim sodales ut eu sem integer vitae. Urna nunc id cursus metus aliquam. Tincidunt augue interdum velit euismod in pellentesque massa. Facilisis gravida neque convallis a cras semper auctor neque.

  Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Placerat in egestas erat imperdiet sed. Amet risus nullam eget felis eget nunc lobortis. Arcu non odio euismod lacinia at quis risus sed. Lacus laoreet non curabitur gravida arcu. Mi quis hendrerit dolor magna eget est lorem. Ut etiam sit amet nisl purus in. Aliquam sem fringilla ut morbi tincidunt augue. Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. Quis enim lobortis scelerisque fermentum dui faucibus in ornare. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit.

  Sem integer vitae justo eget magna. Amet aliquam id diam maecenas ultricies. Et tortor consequat id porta nibh venenatis cras sed felis. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus mauris. Arcu bibendum at varius vel pharetra vel turpis nunc. Enim sed faucibus turpis in. Habitant morbi tristique senectus et netus. At elementum eu facilisis sed odio. Sagittis orci a scelerisque purus semper eget duis at tellus. Magna eget est lorem ipsum. Libero volutpat sed cras ornare arcu dui. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Vel facilisis volutpat est velit egestas dui id ornare arcu. Enim tortor at auctor urna nunc id. Pellentesque id nibh tortor id aliquet lectus. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Tempus iaculis urna id volutpat lacus.

  Dui vivamus arcu felis bibendum ut. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Ac placerat vestibulum lectus mauris ultrices. Turpis nunc eget lorem dolor sed viverra ipsum nunc. Amet aliquam id diam maecenas ultricies mi eget mauris pharetra. Fringilla ut morbi tincidunt augue. Tincidunt lobortis feugiat vivamus at. Mi sit amet mauris commodo quis imperdiet massa. Libero volutpat sed cras ornare arcu. Velit aliquet sagittis id consectetur purus. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Hendrerit dolor magna eget est lorem ipsum dolor.
</div>
<?php
  echo file_get_contents("html\bottom.html");
?>
